### ISSUE TITLE
Cross-tick swap example?

### ISSUE THREAD

**Issue by timnugent** [Jeiwan/uniswapv3-code#1]
Really enjoying reading your book - I don't suppose you have a python example for a cross-tick swap?

**Comment by Jeiwan** [comment]
I used the Python script to demonstrate how Uniswap math works before implementing it in Solidity. Implementing cross-tick swaps in Python would require implementing the entire swapping mechanism, which is out of the scope of this book :) It's basically the same swapping math and logic but it requires injecting/removing liquidity when getting out of or moving into a price range.

**Comment by timnugent** [comment]
No probs - I ended up porting alll of the tickmath and swapmath Solidity code to c++, quite a big effort (but good to really understand what's going on) - but yes can understand it's beyond the scope of the book
