### ISSUE TITLE
Contract size above the EP-170 limit

### ISSUE THREAD

**Issue by Lockwu6749** [Jeiwan/uniswapv3-code#13]
After running the "make deploy" I am getting this message:

`Unknown5` is above the EIP-170 contract size limit (25912 > 24576).
Do you wish to continue?

If I select yes, it deploys nearly all the contracts, but comes back with an error:
Error: 
Transaction Failure: 0x08ad04406e387c8cc91d66b4d746aa069d8c5c9f1f3b8cf1048a61acbe8784a4
make: *** [Makefile:4: deploy] Error 1

**Comment by hephzibah-cmd** [comment]
have you found a solution to this? i have the same error

**Comment by jinbinhan** [comment]
Have the same problem and didn't work with "anvil --code-size-limit 48576".

**Comment by Jeiwan** [comment]
`code-size-limit` needs to be added both to the Anvil and the deployment commands. Fixed:
https://github.com/Jeiwan/uniswapv3-book/commit/29eceff22b3344320271dd9e16ed39af5aaef915
