### ISSUE TITLE
step.initialized not checked in pool swap function

### ISSUE THREAD

**Issue by bzpassersby** [Jeiwan/uniswapv3-code#14]
Thanks for the great work! But I see that in the `swap` function (milestone 5) in the pool contract, there is no checking on whether `step.nextTick` returned by `nextInitializedTickWithinOneWord` is initialized or not. Neither was this checked before invoking `ticks. cross()` later in the same function.  This means that whenever a tick is crossed from the next word, regardless of whether the tick is bound for a liquidity position or not, the state of the tick is rewritten, this will cost a lot of gas, right? 

I think the `step.nextTick` s state of initialization needs to be checked before invoking 'ticks.cross()', unless there is some reason I missed? Also from Uniswapv3 white paper, it says  '𝑓𝑜 is only needed for ticks that are used as either the lower or
upper bound for at least one position. As a result, for efficiency, 𝑓𝑜 is
not initialized (and thus does not need to be updated when crossed)
until a position is created that has that tick as one of its bounds.'

Thank you!

**Comment by Jeiwan** [comment]
Thanks for reporting! Fixed: https://github.com/Jeiwan/uniswapv3-code/commit/2cfc4dacef54cba6fdcf44941a43a09c6fbac9f2
