### ISSUE TITLE
Error in a sentence in Milestone2:Tick Bitmap Index ?

### ISSUE THREAD

**Issue by merdan-9** [Jeiwan/uniswapv3-code#16]
> taking next tick’s word and bit positions;
making a different mask, where all bits to the left of **next tick bit** position are ones and all the bits to the right are zeros;
applying the mask to the next tick’s word.

I think it should be the left of the current bit position?

**Comment by Jeiwan** [comment]
Thanks! Fixed:
https://github.com/Jeiwan/uniswapv3-book/commit/1e51b7cc770d677212816bdecda0f1fffcf6572a
