### ISSUE TITLE
issue of foundry deployment

### ISSUE THREAD

**Issue by Jsoooooooo** [Jeiwan/uniswapv3-code#7]
Hello,

there is an issue occurring while deploying the original swap-05 scripts, which is shown as below. Could you please tell what I can do to fix it ?

kind regards.

<img width="1280" alt="截屏2022-10-20 15 19 28" src="https://user-images.githubusercontent.com/104627404/196882277-7d670d66-2e5e-4c12-92e5-3bab405a0e83.png">

**Comment by Jeiwan** [comment]
This one was addresses here:
https://github.com/Jeiwan/uniswapv3-code/issues/4

You need to ensure the tokens are sorted correctly. This is explained in this paragraph (see the second quote):
https://uniswapv3book.com/docs/milestone_4/factory-contract/#factory-implementation

**Comment by Jsoooooooo** [comment]
Thanks a lot, appreciate!!.

Many thanks
