### ISSUE TITLE
Wrong variable referenced in scr/lib/Tick.sol

### ISSUE THREAD

**Issue by allenzhao** [Jeiwan/uniswapv3-code#8]
As I was going through the book, I found that the variable for calculating `feeGrowthBelow1X128` and `feeGrowthAbove1X128` (See, for example [here](https://github.com/Jeiwan/uniswapv3-code/blob/c66dd66618eb80c665812e644845cd390d4a8402/src/lib/Tick.sol#L96)) are using the wrong starting point for calculation, i.e. the referenced line should be `feeGrrowthGlobal1X128` instead of `feeGrrowthGlobal0X128`

**Comment by Jeiwan** [comment]
Thanks! Fixed!
