### ISSUE TITLE
Can't resolve 'ngraph.graph' in ./src/lib/pathFinder.js 3:0-39

### ISSUE THREAD

**Issue by sun1211** [Jeiwan/uniswapv3-code#9]
after run `yarn & yarn start`

```
ERROR in ./src/lib/pathFinder.js 3:0-39
Module not found: Error: Can't resolve 'ngraph.graph' in '~/uniswapv3-code/ui/src/lib'
```

Notes: I already  run`yarn add ngraph.path` but it does not work

Can not start UI

**Comment by kingofclubstroyDev** [comment]
I ran:
npm install ngraph.path

which seemed to resolve it

**Comment by Jeiwan** [comment]
You need to run `yarn` in the `ui` folder:
```shell
$ cd ui
$ yarn
$ yarn start
```

**Comment by 0xfuturistic** [comment]
seems to work using npm
